Iteracion3/SistemaWeb_version2.0/workspace/config/routes.rb
Rails.application.routes.draw do
  

  get 'buscar_paciente_enfermedad/index'

  get 'buscar_paciente_enfermedad/create'

  get 'buscar_paciente_cita/index'
  get 'buscar_paciente_cita/create'

  get 'buscarmedico/create'

  get 'buscarmedico/index'

  root  "inicio#index"

  get 'buscarpaciente/index'

  get 'buscarpaciente/create'

  resources :cita
  resources :enfermedads
  devise_for :medicos, :controllers => { :registrations => "medicos/registrations", :sessions => "medicos/sessions"}
  resources :pacientes do
    resources :cita, :controller => "paciente_citas" do
      resources :observacions, :controller => "paciente_cita_observacions"
    end
    resources :observacions, :controller => "paciente_observacions"
    resources :enfermedads, :controller => "paciente_enfermedades", only: [:index, :new, :create, :destroy]
  end
  resources :medicos, only: [:show, :edit, :update, :index, :destroy]

  
  
  delete 'telefonos/:id(.:format)', :to => 'telefonos#destroy'
  delete 'emails/:id(.:format)', :to => 'emails#destroy'
  
  
  

end

Iteracion3/SistemaWeb_version2.0/workspace/app/controllers/paciente_cita_observacions_controller.rb
class PacienteCitaObservacionsController < ApplicationController
  before_action :authenticate_medico!
  before_action :authorize_medico, only: [:show, :edit, :update, :destroy, :index, :new, :create]
  
  def index
    @paciente = Paciente.find(params[:paciente_id])
    @cita = Citum.find(params[:citum_id])
    @observacions = @cita.observacions.paginate(page: params[:page], :per_page => 15)
  end

  def new
    @paciente = Paciente.find(params[:paciente_id])
    @cita = Citum.find(params[:citum_id])
    @observacion = @cita.observacions.new
  end
  
  def create 
    @cita = Citum.find(params[:citum_id])
    @paciente = Paciente.find(params[:paciente_id])
    @observacion = Observacion.new
    @observacion.descripcion = params[:observacion][:descripcion]
    @observacion.medico_id = current_medico.id
    @observacion.created_at = Time.now
    respond_to do |format|
       if @observacion.save
         @cita.observacions << @observacion
         format.html { redirect_to paciente_citum_observacions_path(@paciente,@cita), notice: 'Observación fue creada exitosamente.' }
       else
         format.html { redirect_to new_paciente_citum_observacion_path(@paciente,@cita), notice: 'Error al crear observación'}
       end
     end
  end
  
  def show
    @paciente = Paciente.find(params[:paciente_id])
    @cita = Citum.find(params[:citum_id])
    @observacion = Observacion.find(params[:id])
  end

  def edit
    @paciente = Paciente.find(params[:paciente_id])
    @cita = Citum.find(params[:citum_id])
    @observacion = Observacion.find(params[:id])
  end
  
  def update
    @cita = Citum.find(params[:citum_id])
    @paciente = Paciente.find(params[:paciente_id])
    @observacion = Observacion.find(params[:id])
    @observacion.descripcion = params[:observacion][:descripcion]
    @observacion.medico_id = current_medico.id
    @observacion.created_at = Time.now
    respond_to do |format|
       if @observacion.update(observacion_params)
         format.html { redirect_to paciente_citum_observacions_path(@paciente,@cita), notice: 'Observación fue actualizada exitosamente.' }
       else
         format.html { redirect_to new_paciente_citum_observacion_path(@paciente,@cita), notice: 'Error al crear observación'}
       end
     end
  end

  def destroy
    @cita = Citum.find(params[:citum_id])
    @paciente = Paciente.find(params[:paciente_id])
    @observacion = @cita.observacions.find(params[:id])
    Observacion.delete(@observacion)
    @cita.observacions.delete(@observacion)
      respond_to do |format|
      format.html { redirect_to paciente_citum_observacions_path(@paciente,@cita), notice: 'Observación fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end
  
  
  private
  
    def observacion_params
      params.require(:observacion).permit(:descripcion)
    end
  
    def authorize_medico
      if current_medico.pacientes.exists?(['id LIKE ?', "%#{params[:paciente_id]}%"])
      else
        respond_to do |format|
          format.html { redirect_to pacientes_path }
        end
      end
    end
    
end

Iteracion3/SistemaWeb_version2.0/workspace/app/helpers/paciente_cita_observacions_helper.rb
module PacienteCitaObservacionsHelper
end

Iteracion3/SistemaWeb_version2.0/workspace/app/views/paciente_cita_observacions/_form.html.erb
<%= form_for([@paciente,@cita,@observacion]) do |f| %>
  <% if @observacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observacion.errors.count, "error") %> error al ingresar:</h2>

      <ul>
      <% @observacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion, "Descripción" %>
    <%= f.text_area :descripcion, :placeholder => "Descripción" %>
  </div>
  <hr/>
  <div class="actions">
    <% if @observacion.new_record? %>
        <%= f.submit "Registrar", :class => "button special" %>
      <% else %>
        <%= f.submit "Editar", :class => "button special" %>
      <% end %>
  </div>
<% end %>

Iteracion3/SistemaWeb_version2.0/workspace/app/views/paciente_cita_observacions/edit.html.erb
<% if medico_signed_in? %>

    <span class="image right">
        <%= link_to 'Regresar', paciente_citum_observacions_path(@paciente,@cita), :class => "button small icon fa-arrow-left"%>
    </span>

    <h1>Editar observación</h1>
     <hr/> 
    
    <%= render 'form' %>
    

<% end %>

Iteracion3/SistemaWeb_version2.0/workspace/app/views/paciente_cita_observacions/index.html.erb
  <p id="notice"><%= notice %></p>
  
  <span class="image right">
     <%= link_to 'Regresar', paciente_cita_path(@paciente), :class => "button small icon fa-arrow-left" %>
  </span>
  
  <h1>Observaciones de la cita</h1>
  
      <div class="row">
          <div class="4u 12u(small)">
            <%= link_to 'Nueva observación', new_paciente_citum_observacion_path(@paciente,@cita), :class => "button special small fit icon fa-plus" %>
          </div>   
      </div> 
      
    <hr/>
    
  <h2>Paciente:<%= " " %> <%= @paciente.nombre %><%= " " %><%= @paciente.apellido1 %><%= " " %><%= @paciente.apellido2 %></h2>
  <div class="table-wrapper">
     <table class="alt">
      <thead>
        <tr>
          <th>Médico</th>
          <th>Fecha</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @observacions.each do |observacion| %>
          <tr>
            <td><%= observacion.medico.nombre %><%= " " %><%= observacion.medico.apellido1 %><%= " " %><%= observacion.medico.apellido2 %></td>
            <td><%= observacion.created_at %></td>
            <td><%= link_to 'Mostrar', paciente_citum_observacion_path(@paciente,@cita,observacion), :class => "button small fit icon fa-file-text-o" %></td>
            <td><%= link_to 'Editar', edit_paciente_citum_observacion_path(@paciente,@cita,observacion), :class => "button small fit icon fa-edit" %></td>
            <td><%= link_to 'Eliminar',  paciente_citum_observacion_path(@paciente,@cita,observacion), method: :delete, :class => "button small fit icon fa-remove", data: { confirm: 'Desea continuar?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
 
  <br/>
  
  <%= will_paginate @observacions, renderer: BootstrapPagination::Rails %>
  

Iteracion3/SistemaWeb_version2.0/workspace/app/views/paciente_cita_observacions/new.html.erb
<% if medico_signed_in? %>

    <span class="image right">
        <%= link_to 'Regresar', paciente_citum_observacions_path(@paciente,@cita), :class => "button small icon fa-arrow-left"%>
    </span>
    <h1>Nueva observación</h1>
     <hr/> 
    
    <%= render 'form' %>
    
    
<% end %>

Iteracion3/SistemaWeb_version2.0/workspace/app/views/paciente_cita_observacions/show.html.erb
<% if medico_signed_in? %>
  <p id="notice"><%= notice %></p>
  
  <span class="image right">
     <%= link_to 'Regresar', paciente_citum_observacions_path(@paciente,@cita), :class => "button small icon fa-arrow-left" %>
  </span>
            
  <h1>Detalles de la observación</h1>
  
    <div class="row">
        <div class="4u 12u(small)">
            <%= link_to 'Editar', edit_paciente_citum_observacion_path(@paciente,@cita,@observacion), :class => "button small fit special icon fa-edit" %> 
        </div>   
    </div> 
    
    <hr/>
    
   <h2>Paciente:<%= " " %> <%= @paciente.nombre %><%= " " %><%= @paciente.apellido1 %><%= " " %><%= @paciente.apellido2 %></h2>
  
   <header>
    <h2>Médico:</h2>
    <p><%= @observacion.medico.nombre %><%= " " %><%= @observacion.medico.apellido1 %><%= " " %><%= @observacion.medico.apellido2 %></p>
  </header>
  
  <header>
    <h2>Fecha:</h2>
    <p><%= @observacion.created_at %></p>
  </header>
    
  <header>
    <h2>Descripción:</h2>
    <blockquote><%= @observacion.descripcion %></blockquote>
  </header>
 
  
<% end %>