Iteracion1/SistemaWeb_version1.0/workspace/config/routes.rb
Rails.application.routes.draw do
  

  get 'buscar_paciente_enfermedad/index'

  get 'buscar_paciente_enfermedad/create'

  get 'buscar_paciente_cita/index'
  get 'buscar_paciente_cita/create'

  get 'buscarmedico/create'

  get 'buscarmedico/index'

  root  "inicio#index"

  get 'buscarpaciente/index'

  get 'buscarpaciente/create'

  resources :cita
  resources :enfermedads
  devise_for :medicos, :controllers => { :registrations => "medicos/registrations" }
  resources :pacientes do
    resources :cita, :controller => "paciente_citas" do
      resources :observacions, :controller => "paciente_cita_observacions"
    end
    resources :observacions, :controller => "paciente_observacions"
    resources :enfermedads, :controller => "paciente_enfermedades", only: [:index, :new, :create, :destroy]
  end
  resources :medicos, only: [:show, :edit, :update, :index, :destroy]

  
  
  delete 'telefonos/:id(.:format)', :to => 'telefonos#destroy'
  delete 'emails/:id(.:format)', :to => 'emails#destroy'
  
  
  

end

Iteracion1/SistemaWeb_version1.0/workspace/app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  before_action :authenticate_medico!
  def index
  end
end

Iteracion1/SistemaWeb_version1.0/workspace/app/helpers/inicio_helper.rb
module InicioHelper
end

Iteracion1/SistemaWeb_version1.0/workspace/app/views/inicio/index.html.erb
<% if medico_signed_in? %>
<p id="notice"><%= notice %></p>
    <h1>Bienvenido</h1>
    <h3>
    <% if !current_medico.has_role? :admin %>
        Dr. 
    <% end %>
      <%= " " %> <%= current_medico.nombre %><%= " " %><%= current_medico.apellido1 %><%= " " %><%= current_medico.apellido2 %>
    
    </h3>
    
    
    <p> Fecha: <%= Time.now %> </p>
<% end %>