Iteracion1/SistemaWeb_version1.0/workspace/config/routes.rb
Rails.application.routes.draw do
  

  get 'buscar_paciente_enfermedad/index'

  get 'buscar_paciente_enfermedad/create'

  get 'buscar_paciente_cita/index'
  get 'buscar_paciente_cita/create'

  get 'buscarmedico/create'

  get 'buscarmedico/index'

  root  "inicio#index"

  get 'buscarpaciente/index'

  get 'buscarpaciente/create'

  resources :cita
  resources :enfermedads
  devise_for :medicos, :controllers => { :registrations => "medicos/registrations" }
  resources :pacientes do
    resources :cita, :controller => "paciente_citas" do
      resources :observacions, :controller => "paciente_cita_observacions"
    end
    resources :observacions, :controller => "paciente_observacions"
    resources :enfermedads, :controller => "paciente_enfermedades", only: [:index, :new, :create, :destroy]
  end
  resources :medicos, only: [:show, :edit, :update, :index, :destroy]

  
  
  delete 'telefonos/:id(.:format)', :to => 'telefonos#destroy'
  delete 'emails/:id(.:format)', :to => 'emails#destroy'
  
  
  

end

Iteracion1/SistemaWeb_version1.0/workspace/app/controllers/paciente_enfermedades_controller.rb
class PacienteEnfermedadesController < ApplicationController
  before_action :authenticate_medico!
  
  def index
    @paciente = Paciente.find(params[:paciente_id])
    @enfermedads = @paciente.enfermedads.paginate(page: params[:page], :per_page => 10)
  end

  def new
    @enfermedads = Enfermedad.all
    @paciente = Paciente.find(params[:paciente_id])
    @enfermedad = @paciente.enfermedads.new
  end
  
  
  def create
    @paciente = Paciente.find(params[:paciente_id])
    respond_to do |format|
       if @paciente.enfermedads.exists?(params[:enfermedad][:id])
          format.html { redirect_to new_paciente_enfermedad_path(@paciente), notice: 'No se aceptan enfermedades ya ingresadas'}
       else
         @paciente.enfermedads << Enfermedad.find(params[:enfermedad][:id])
         format.html { redirect_to paciente_enfermedads_path(@paciente), notice: 'Enfermedad fue asignada exitosamente.' }
       end
     end
  end
  
  def destroy
     @paciente = Paciente.find(params[:paciente_id])
     @enfermedad = @paciente.enfermedads.find(params[:id])
     @paciente.enfermedads.delete(@enfermedad)
      respond_to do |format|
      format.html { redirect_to paciente_enfermedads_path(@paciente), notice: 'Enfermedad fue eliminada del paciente exitosamente.' }
      format.json { head :no_content }
    end
  end
 
end

Iteracion1/SistemaWeb_version1.0/workspace/app/helpers/paciente_enfermedades_helper.rb
module PacienteEnfermedadesHelper
end

Iteracion1/SistemaWeb_version1.0/workspace/app/views/paciente_enfermedades/_form.html.erb
<%= form_for([@paciente,@enfermedad]) do |f| %>

 <% if @enfermedad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enfermedad.errors.count, "error") %> error al ingresar:</h2>

      <ul>
      <% @enfermedad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
 <h3>Enfermedad</h3>
  <section id="two">
        <%= f.select :id,  options_from_collection_for_select(@enfermedads, 'id', 'descripcion') %>
  </section>
  <hr/>
  <div class="actions">
    <%= f.submit "Finalizar", :class => "button special" %>
  </div>
<% end %>

Iteracion1/SistemaWeb_version1.0/workspace/app/views/paciente_enfermedades/index.html.erb
  <p id="notice"><%= notice %></p>
  
  <div class="row">
          <div class="8u 12u(small)">
              <h1>Lista de enfermedades</h1>
          </div> 
          <div class="4u$ 12u$(small)">
            <%= link_to 'Agregar enfermedad', new_paciente_enfermedad_path(@paciente), :class => "button special small fit icon fa-ambulance" %>
          </div>   
      </div> 
      
    <hr/>
    
   <h2>Paciente:<%= " " %> <%= @paciente.nombre %><%= " " %><%= @paciente.apellido1 %><%= " " %><%= @paciente.apellido2 %></h2>
  <div class="table-wrapper">
     <table class="alt">
      <thead>
        <tr>
          <th>Codigo</th>
          <th>Descripcion</th>
          <th colspan="2"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @enfermedads.each do |enfermedad| %>
          <tr>
            <td><%= enfermedad.codigo %></td>
            <td><%= enfermedad.descripcion %></td>
            <td><%= link_to 'Mostrar', enfermedad, :class => "button small fit icon fa-file-text-o" %></td>
            <td><%= link_to 'Eliminar',  paciente_enfermedad_path(@paciente, enfermedad), method: :delete, :class => "button special small fit icon fa-remove", :style => "background-color:#f56a6a;border-color:#f56a6a;" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  
  <br/>
  
  <%= will_paginate @enfermedads, renderer: BootstrapPagination::Rails %>
  

Iteracion1/SistemaWeb_version1.0/workspace/app/views/paciente_enfermedades/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Agregar enfermedad</h1>

 <h2>Paciente:<%= " " %> <%= @paciente.nombre %><%= " " %><%= @paciente.apellido1 %><%= " " %><%= @paciente.apellido2 %></h2>

<%= render 'form' %>

<%= link_to 'Regresar', paciente_enfermedads_path(@paciente), :class => "button small icon fa-arrow-left" %>